name: jestTest

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Jest tests
      run: npm run test-unit
