name: Node.js CI

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run test-unit
